POST http://localhost:3000/productos
Content-Type: application/json

{
  "nombre": "Granizado de Mango",
  "precio": 5000,
  "stock": 20
}
###

GET http://localhost:3000/productos
###

PUT http://localhost:3000/productos/1
Content-Type: application/json

{
  "nombre": "Granizado de Mango Grande",
  "precio": 6000,
  "stock": 25
}

###

DELETE http://localhost:3000/productos/1
###

POST http://localhost:3000/usuarios
Content-Type: application/json

{
  "nombre": "Nicolas",
  "email": "nicolas@granizados.com",
  "password": "123456",
  "rol": "Administrador"
}
###

GET http://localhost:3000/usuarios
###

PUT http://localhost:3000/usuarios/1
Content-Type: application/json

{
  "nombre": "Nicolas Moreno",
  "email": "nicolas@granizados.com",
  "password": "123456",
  "rol": "Administrador"
}