POST http://localhost:3000/productos
Content-Type: application/json

{
  "nombre": "Granizado de Mango",
  "precio": 5000,
  "stock": 20
}
###

GET http://localhost:3000/productos
###

PUT http://localhost:3000/productos/1
Content-Type: application/json

{
  "nombre": "Granizado de Mango Grande",
  "precio": 6000,
  "stock": 25
}

###

DELETE http://localhost:3000/productos/1
###

POST http://localhost:3000/usuarios
Content-Type: application/json

{
  "nombre": "Nicolas",
  "email": "nicolas@granizados.com",
  "password": "123456",
  "rol": "Administrador"
}
###

GET http://localhost:3000/usuarios
###

PUT http://localhost:3000/usuarios/1
Content-Type: application/json

{
  "nombre": "Nicolas Moreno",
  "email": "nicolas@granizados.com",
  "password": "123456",
  "rol": "Administrador"
}
###

DELETE http://localhost:3000/usuarios/1
###

POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "nicolas@granizados.com",
  "password": "123456"
}
###

POST http://localhost:3000/usuarios
Content-Type: application/json

{
  "nombre": "Nicolas",
  "email": "nicolas@granizados.com",
  "password": "123456",
  "rol": "Administrador"
}
###

POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "nicolas@granizados.com",
  "password": "123456"
}

###

PUT http://localhost:3000/productos/1/stock
Content-Type: application/json

{
  "stock": 50
}

###

GET http://localhost:3000/productos

###

POST http://localhost:3000/productos
Content-Type: application/json

{
  "nombre": "Granizado de Mango",
  "precio": 5000,
  "stock": 20
}

###

GET http://localhost:3000/

###

PUT http://localhost:3000/productos/2/stock
Content-Type: application/json

{
  "stock": 50
}

###

GET http://localhost:3000/productos
###

POST http://localhost:3000/ventas
Content-Type: application/json

{
  "producto_id": 2,
  "cantidad": 3
}

###

GET http://localhost:3000/productos